Repository reustle/covid19japan, pull requests merged in 2020-07, with the labels that each got.

#366 Make the time period for the DailyIncrease and SpreadTrend dynamic
  src/components/DailyIncreaseChart/DailyIncrease.js
  src/components/SpreadTrendChart/SpreadTrend.js
  src/data/constants.js
  src/index.js
Labels: enhancement

#364 Added Ukrainian localization
  src/i18n/index.js
  src/i18n/uk.json
Labels: localization

#338 Include Arabic Language (Need Help)
  src/i18n/ar.json
  src/i18n/index.js
Labels: localization

#360 I18n number formatting
  src/components/DailyIncreaseChart/DailyIncrease.js
  src/components/Header/DrawPageTitleCount.js
  src/components/Kpi/DrawKpis.js
  src/components/OutbreakMap/DrawMapPrefectures.js
  src/components/OutbreakMap/_map.scss
  src/components/PrefectureTable/PrefectureTable.js
  src/components/SpreadTrendChart/SpreadTrend.js
  src/components/TrajectoryChart/TrajectoryChart.js
  src/data/constants.js
  src/i18n/bn.json
  src/i18n/cs.json
  src/i18n/de.json
  src/i18n/en.json
  src/i18n/es.json
  src/i18n/fi.json
  src/i18n/fr.json
  src/i18n/hi.json
  src/i18n/id.json
  src/i18n/it.json
  src/i18n/ja.json
  src/i18n/pl.json
  src/i18n/pt.json
  src/i18n/uk.json
  src/index.html
  src/index.js
Labels: help wanted
